language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install -r tests-require.txt
compiler:
  - gcc
script:
  - python setup.py build
  - pip install .
  - pytest tests/
