language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install -r tests-require.txt
compiler:
  - g++
script:
  - python setup.py build
  - pip install .
  - pytest tests/
  - g++ tests/test_hash_table.cpp xswap/hash_table.cpp -o tests/test_hash_table.o -std=c++11
  - ./tests/test_hash_table.o
  - cat tests/permutation_stats.txt
