dist: xenial
language: python
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install -r tests-require.txt
addons:
  apt:
    packages:
      - pkg-config
      - python3-dev
compiler:
  - g++
script:
  - pkg-config --cflags --libs python3
  - python setup.py build
  - pip install .
  - pytest tests/
  - >
      g++ tests/test_bitset.cpp xswap/src/xswap.h xswap/src/bitset.cpp
      xswap/lib/roaring.c -o tests/test_bitset.o -std=c++11
      `pkg-config --cflags --libs python3`
  - ./tests/test_bitset.o
  - >
      g++ tests/test_roaring.cpp xswap/src/xswap.h xswap/src/bitset.cpp
      xswap/lib/roaring.c -o tests/test_roaring.o -std=c++11
      `pkg-config --cflags --libs python3`
  - ./tests/test_roaring.o
  - cat tests/permutation_stats.txt
