language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - sudo apt-get install python3-dev
  - pip install -r tests-require.txt
compiler:
  - g++
script:
  - python setup.py build
  - pip install .
  - pytest tests/
  - g++ tests/test_bitset.cpp xswap/src/bitset.cpp xswap/lib/roaring.c -o tests/test_bitset.o -std=c++11
  - ./tests/test_bitset.o
  - g++ tests/test_roaring.cpp xswap/lib/roaring.c xswap/src/bitset.cpp -o tests/test_roaring.o -std=c++11
  - ./tests/test_roaring.o
  - cat tests/permutation_stats.txt
