language: python
python:
  - 3.5
  - 3.6
  - 3.7-dev
install:
  - pip install -r tests-require.txt
addons:
  apt:
    packages:
      - python3-dev
compiler:
  - g++
script:
  - python setup.py build
  - pip install .
  - pytest tests/
  - ls /usr/include/
  - g++ tests/test_bitset.cpp xswap/src/bitset.cpp xswap/lib/roaring.c -o tests/test_bitset.o -std=c++11 -I/usr/include/python3.6m
  - ./tests/test_bitset.o
  - g++ tests/test_roaring.cpp xswap/lib/roaring.c xswap/src/bitset.cpp -o tests/test_roaring.o -std=c++11 -I/usr/include/python3.6m
  - ./tests/test_roaring.o
  - cat tests/permutation_stats.txt
